version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 core.py'
    env_file:
      - .env
    environment:
      CLOUDAMQP_URL: $CLOUDAMQP_URL
    ports:
      - 5001:5001
    volumes:
      - .:/backendservice
    depends_on:
      db:
        condition: service_healthy
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CLOUDAMQP_URL: $CLOUDAMQP_URL
    command: 'python3 -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
      MYSQL_ROOT_PASSWORD: microservice
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

volumes:
  dbdata: